server:
  servlet:
    context-path: /management
  port: 8080

spring:
  application:
    name: comprehensiveReqManager
  datasource:
#    url: jdbc:mysql://localhost:3306/emo?&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:kingbase8://localhost:54321/emo?serverTimezone=GMT%2B8
    driver-class-name: com.kingbase8.Driver
    username: root
    password: root
    hikari:
      pool-name: spring-demo-1 #连接池名称
      connection-timeout: 60000 #请求连接的超时时间
      maximum-pool-size: 1 #最大连接数量
      max-lifetime: 1800000 #连接的最长生命周期
      keepalive-time: 1750000 #尝试保持连接的频率
      connection-test-query: select 1 #连接验证sql
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full #自动映射的配置属性和数据库列相同不用配置result
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      date-format: yyyy-MM-dd HH:mm:ss


redis:

  host: 127.0.0.1
  port: 6379
  #password: 123456
  database: 0 #操作的是0号数据库
  jedis:
  #Redis连接池配置
   pool:
      max-active: 1 #最大连接数
      max-wait: 1ms #连接池最大阻塞等待时间
      max-idle: 1 #连接池中的最大空闲连接

mysql:
  entitySql: Select * from entity;
  valueSql: SELECT v.attribute_id,v.entity_id,v.value,value_id,a.attribute_id,a.attribute_name FROM value v  JOIN attribute a  ON v.attribute_id = a.attribute_id;
  attributeSql: Select * from attribute;
  relationshipSql: Select * from relationship;
#  valueSql: Select * from value;

upload:
#  path: /usr/local/upload/avatar
  # 上传的图片保存路径（可自定义）
  path: D://upload//avatar//

service:
  ip: 127.0.0.1
  port: 80



